require "phase/cli/command"

require "phase/cli/env"
require "phase/cli/deploy"
require "phase/cli/keys"
require "phase/cli/ipa"
require "phase/cli/logs"
require "phase/cli/ssh"
require "phase/cli/mosh"
require "phase/cli/status"
